language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- npm run test:headless
- ng build --prod --base-href /lidikart-v2/
- cp dist/lidikart-v2/index.html dist/lidikart-v2/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/lidikart-v2
  on:
    branch: master
